--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

local group = AttachedLocations.getGroup("Human")
group:getOrCreateLocation("Balloon Left"):setAttachmentName("Bip01_L_Shoulder")
group:getOrCreateLocation("Balloon Right"):setAttachmentName("Bip01_R_Shoulder")
group:getOrCreateLocation("Balloon Center"):setAttachmentName("Neck_Balloon")
group:getOrCreateLocation("Canteen Left"):setAttachmentName("Canteen_L")
group:getOrCreateLocation("Canteen Right"):setAttachmentName("Canteen_R")
group:getOrCreateLocation("Item Slot 1"):setAttachmentName("Pills_L")
group:getOrCreateLocation("Item Slot 2"):setAttachmentName("Pills_R")
group:getOrCreateLocation("Pills Right"):setAttachmentName("Pills_R")
group:getOrCreateLocation("Pills Left"):setAttachmentName("Pills_L")
group:getOrCreateLocation("Pipe Waist"):setAttachmentName("Pipe_Waist")
group:getOrCreateLocation("Left Hand"):setAttachmentName("Bip01_L_Finger1")
group:getOrCreateLocation("Left Hand Item"):setAttachmentName("stop_sign_left")
group:getOrCreateLocation("Right Hand"):setAttachmentName("Bip01_R_Finger0")
group:getOrCreateLocation("Right Hand1"):setAttachmentName("Bip01_R_Finger1")
group:getOrCreateLocation("Right Hand Item"):setAttachmentName("stop_sign_right")
group:getOrCreateLocation("BucketHead"):setAttachmentName("Bip01_Head")
group:getOrCreateLocation("PlungerFace"):setAttachmentName("AZ_PlungerFace")
group:getOrCreateLocation("PlungerHead"):setAttachmentName("AZ_PlungerHead")
group:getOrCreateLocation("MinerLight"):setAttachmentName("knife_head")
group:getOrCreateLocation("Military Flashlight Left"):setAttachmentName("MilitaryFlashlight_L")
group:getOrCreateLocation("Military Flashlight Right"):setAttachmentName("MilitaryFlashlight_R")
group:getOrCreateLocation("Paper Left"):setAttachmentName("Paper_left")
group:getOrCreateLocation("Paper Right"):setAttachmentName("Paper_right")
group:getOrCreateLocation("WalkieTalkie Left"):setAttachmentName("WalkieTalkie_L")
group:getOrCreateLocation("WalkieTalkie Right"):setAttachmentName("WalkieTalkie_R")
group:getOrCreateLocation("CherryLeg"):setAttachmentName("Cherry_Leg_R")

-- Backpack attachments --
group:getOrCreateLocation("Flare Gun Left"):setAttachmentName("BackPack_Flare_Left")
group:getOrCreateLocation("Flare Gun Right"):setAttachmentName("BackPack_Flare_Right")

-- Webbing attachments --
group:getOrCreateLocation("Webbing Rope Left_AZ"):setAttachmentName("Webbing_Rope_Left_AZ")
group:getOrCreateLocation("Webbing SheetRope Left_AZ"):setAttachmentName("Webbing_SheetRope_Left_AZ")
group:getOrCreateLocation("Webbing FlareGun Left_AZ"):setAttachmentName("Webbing_FlareGun_Left_AZ")
group:getOrCreateLocation("Webbing Explosive Left_AZ"):setAttachmentName("Webbing_Explosive_Left_AZ")
group:getOrCreateLocation("Webbing AuthenticExplosive Left_AZ"):setAttachmentName("Webbing_AuthenticExplosive_Left_AZ")
group:getOrCreateLocation("Webbing GasMask Left_AZ"):setAttachmentName("Webbing_GasMask_Left_AZ")
group:getOrCreateLocation("Webbing Walkie Left_AZ"):setAttachmentName("Webbing_Walkie_Left_AZ")
group:getOrCreateLocation("Webbing Hammer Left_AZ"):setAttachmentName("Webbing_Hammer_Left_AZ")
group:getOrCreateLocation("Webbing Screwdriver Left_AZ"):setAttachmentName("Webbing_Screwdriver_Left_AZ")
group:getOrCreateLocation("Webbing Knife Left_AZ"):setAttachmentName("Webbing_Knife_Left_AZ")
group:getOrCreateLocation("Webbing Saucepan Left_AZ"):setAttachmentName("Webbing_Saucepan_Left_AZ")
group:getOrCreateLocation("Webbing Pan Left_AZ"):setAttachmentName("Webbing_Pan_Left_AZ")
group:getOrCreateLocation("Webbing Wrench Left_AZ"):setAttachmentName("Webbing_Wrench_Left_AZ")
group:getOrCreateLocation("Webbing MeatCleaver Left_AZ"):setAttachmentName("Webbing_MeatCleaver_Left_AZ")
group:getOrCreateLocation("Webbing Waterbottle Left_AZ"):setAttachmentName("Webbing_Waterbottle_Left_AZ")
group:getOrCreateLocation("Webbing Canteen Left_AZ"):setAttachmentName("Webbing_Canteen_Left_AZ")
group:getOrCreateLocation("Webbing Military Flashlight Left_AZ"):setAttachmentName("Webbing_Flashlight_Left_AZ")
group:getOrCreateLocation("Webbing Holster Left_AZ"):setAttachmentName("Webbing_Holster_Left_AZ")

group:getOrCreateLocation("Webbing Rope Right_AZ"):setAttachmentName("Webbing_Rope_Right_AZ")
group:getOrCreateLocation("Webbing SheetRope Right_AZ"):setAttachmentName("Webbing_SheetRope_Right_AZ")
group:getOrCreateLocation("Webbing FlareGun Right_AZ"):setAttachmentName("Webbing_FlareGun_Right_AZ")
group:getOrCreateLocation("Webbing Explosive Right_AZ"):setAttachmentName("Webbing_Explosive_Right_AZ")
group:getOrCreateLocation("Webbing AuthenticExplosive Right_AZ"):setAttachmentName("Webbing_AuthenticExplosive_Right_AZ")
group:getOrCreateLocation("Webbing GasMask Right_AZ"):setAttachmentName("Webbing_GasMask_Right_AZ")
group:getOrCreateLocation("Webbing Walkie Right_AZ"):setAttachmentName("Webbing_Walkie_Right_AZ")
group:getOrCreateLocation("Webbing Hammer Right_AZ"):setAttachmentName("Webbing_Hammer_Right_AZ")
group:getOrCreateLocation("Webbing Screwdriver Right_AZ"):setAttachmentName("Webbing_Screwdriver_Right_AZ")
group:getOrCreateLocation("Webbing Knife Right_AZ"):setAttachmentName("Webbing_Knife_Right_AZ")
group:getOrCreateLocation("Webbing Saucepan Right_AZ"):setAttachmentName("Webbing_Saucepan_Right_AZ")
group:getOrCreateLocation("Webbing Pan Right_AZ"):setAttachmentName("Webbing_Pan_Right_AZ")
group:getOrCreateLocation("Webbing Wrench Right_AZ"):setAttachmentName("Webbing_Wrench_Right_AZ")
group:getOrCreateLocation("Webbing MeatCleaver Right_AZ"):setAttachmentName("Webbing_MeatCleaver_Right_AZ")
group:getOrCreateLocation("Webbing Waterbottle Right_AZ"):setAttachmentName("Webbing_Waterbottle_Right_AZ")
group:getOrCreateLocation("Webbing Canteen Right_AZ"):setAttachmentName("Webbing_Canteen_Right_AZ")
group:getOrCreateLocation("Webbing Military Flashlight Right_AZ"):setAttachmentName("Webbing_Flashlight_Right_AZ")
group:getOrCreateLocation("Webbing Holster Right_AZ"):setAttachmentName("Webbing_Holster_Right_AZ")
