--***********************************************************
--**                    THE INDIE STONE                    **
--***********************************************************

local group = AttachedLocations.getGroup("Human")
group:getOrCreateLocation("Balloon Left"):setAttachmentName("Bip01_L_Shoulder")
group:getOrCreateLocation("Balloon Right"):setAttachmentName("Bip01_R_Shoulder")
group:getOrCreateLocation("Balloon Center"):setAttachmentName("Neck_Balloon")
group:getOrCreateLocation("Flare Gun Left"):setAttachmentName("BackPack_Flare_Left")
group:getOrCreateLocation("Flare Gun Right"):setAttachmentName("BackPack_Flare_Right")
group:getOrCreateLocation("Left Hand"):setAttachmentName("Bip01_L_Finger1")
group:getOrCreateLocation("Left Hand Item"):setAttachmentName("stop_sign_left")
group:getOrCreateLocation("Right Hand"):setAttachmentName("Bip01_R_Finger0")
group:getOrCreateLocation("Right Hand1"):setAttachmentName("Bip01_R_Finger1")
group:getOrCreateLocation("Right Hand Item"):setAttachmentName("stop_sign_right")
group:getOrCreateLocation("BucketHead"):setAttachmentName("Bip01_Head")
group:getOrCreateLocation("Nightstick Left"):setAttachmentName("nightstick_left")
group:getOrCreateLocation("Paper Left"):setAttachmentName("Paper_left")
group:getOrCreateLocation("Paper Right"):setAttachmentName("Paper_right")
group:getOrCreateLocation("Spike Right"):setAttachmentName("Spike_right")
group:getOrCreateLocation("Spike Torso Left 1"):setAttachmentName("winslow_Torso_L_1")
group:getOrCreateLocation("Spike Torso Left 2"):setAttachmentName("winslow_Torso_L_2")
group:getOrCreateLocation("Spike Torso Left 3"):setAttachmentName("winslow_Torso_L_3")
group:getOrCreateLocation("Spike Torso Left 4"):setAttachmentName("winslow_Torso_L_4")
group:getOrCreateLocation("Spike Torso Left 5"):setAttachmentName("winslow_Torso_L_5")
group:getOrCreateLocation("Spike Torso Left 6"):setAttachmentName("winslow_Torso_L_6")
group:getOrCreateLocation("Spike Torso Right 1"):setAttachmentName("winslow_Torso_R_1")
group:getOrCreateLocation("Spike Torso Right 2"):setAttachmentName("winslow_Torso_R_2")
group:getOrCreateLocation("Spike Torso Right 3"):setAttachmentName("winslow_Torso_R_3")
group:getOrCreateLocation("Spike Torso Center 1"):setAttachmentName("winslow_Torso_C_1")
group:getOrCreateLocation("Spike Torso Center 2"):setAttachmentName("winslow_Torso_C_2")
group:getOrCreateLocation("Spike Torso Center 3"):setAttachmentName("winslow_Torso_C_3")
group:getOrCreateLocation("Spike Torso Center 4"):setAttachmentName("winslow_Torso_C_4")
group:getOrCreateLocation("Spike L-Arm 1"):setAttachmentName("winslow_Arm_L_1")
group:getOrCreateLocation("Spike L-Arm 2"):setAttachmentName("winslow_Arm_L_2")
group:getOrCreateLocation("Spike L-Arm 3"):setAttachmentName("winslow_Arm_L_3")
group:getOrCreateLocation("Spike L-Arm 4"):setAttachmentName("winslow_Arm_L_4")
group:getOrCreateLocation("Spike L-Arm 5"):setAttachmentName("winslow_Arm_L_5")
group:getOrCreateLocation("Spike L-Arm 6"):setAttachmentName("winslow_Arm_L_6")
group:getOrCreateLocation("Spike L-Arm 7"):setAttachmentName("winslow_Arm_L_7")
group:getOrCreateLocation("Spike L-Arm 8"):setAttachmentName("winslow_Arm_L_8")
group:getOrCreateLocation("Spike Back 1"):setAttachmentName("winslow_back_1")
group:getOrCreateLocation("Spike Back 2"):setAttachmentName("winslow_back_2")
group:getOrCreateLocation("Spike Back 3"):setAttachmentName("winslow_back_3")
group:getOrCreateLocation("Spike Back 4"):setAttachmentName("winslow_back_4")
group:getOrCreateLocation("Spike Back 5"):setAttachmentName("winslow_back_5")
group:getOrCreateLocation("Spike Back 6"):setAttachmentName("winslow_back_6")
group:getOrCreateLocation("Spike L-Leg 1"):setAttachmentName("winslow_Leg_L_1")
group:getOrCreateLocation("Spike L-Leg 2"):setAttachmentName("winslow_Leg_L_2")
group:getOrCreateLocation("Spike R-Leg 1"):setAttachmentName("winslow_Leg_R_1")
group:getOrCreateLocation("Spike R-Leg 2"):setAttachmentName("winslow_Leg_R_2")
group:getOrCreateLocation("Spike R-Leg 3"):setAttachmentName("winslow_Leg_R_3")
group:getOrCreateLocation("Spike R-Arm 1"):setAttachmentName("winslow_Arm_R_1")
group:getOrCreateLocation("Spike R-Arm 2"):setAttachmentName("winslow_Arm_R_2")
group:getOrCreateLocation("Spike R-Arm 3"):setAttachmentName("winslow_Arm_R_3")
group:getOrCreateLocation("Spike R-Arm 4"):setAttachmentName("winslow_Arm_R_4")
group:getOrCreateLocation("Spike R-Arm 5"):setAttachmentName("winslow_Arm_R_5")
group:getOrCreateLocation("Spike R-Arm 6"):setAttachmentName("winslow_Arm_R_6")
group:getOrCreateLocation("Spike R-Arm 7"):setAttachmentName("winslow_Arm_R_7")
group:getOrCreateLocation("Spike_Gut1"):setAttachmentName("Spike_Gut1_Long")
group:getOrCreateLocation("CherryLeg"):setAttachmentName("Cherry_Leg_R")